(global-set-key (kbd "C-l") 'forward-char)
(global-set-key (kbd "C-j") 'backward-char)
(global-set-key (kbd "M-l") 'forward-word)
(global-set-key (kbd "M-j") 'backward-word)
(global-set-key (kbd "C-c h") 'windmove-left)
(global-set-key (kbd "C-c l") 'windmove-right)
(global-set-key (kbd "C-c C-x m") 'set-mark-command)
(global-set-key (kbd "C-c ;") 'comment-region)
(global-set-key (kbd "C-c /") 'uncomment-region)
(global-set-key (kbd "C-c C-f") 'load-file)
(global-set-key (kbd "C-c C-x s") 'replace-string)
(global-set-key (kbd "C-c C-x <up>") 'enlarge-window-horizontally)
(global-set-key (kbd "C-c C-x <down>") 'shrink-window-horizontally)

(global-set-key (kbd "C-a") 'hs-smart-beginning-of-line)
(global-set-key (kbd "C-c C-x ;") 'hs-comment-line)
(global-set-key (kbd "C-c C-x /") 'hs-uncomment-line)
(global-set-key (kbd "C-c C-x f") 'hs-show-file-path)
(global-set-key (kbd "C-c C-x b") 'hs-show-buffer-name)
(global-set-key (kbd "C-c C-x k") 'hs-backward-kill-line)
(global-set-key (kbd "C-c C-x w") 'hs-move-beginning-of-first-word)
(global-set-key (kbd "C-c C-x l") 'hs-select-stripped-line)
(global-set-key (kbd "C-c C-x d") 'hs-kill-stripped-line)
(global-set-key (kbd "C-c C-x x") 'hs-kill-whole-line)
