(global-set-key (kbd "C-l") 'forward-char)
(global-set-key (kbd "C-j") 'backward-char)
(global-set-key (kbd "M-l") 'forward-word)
(global-set-key (kbd "M-j") 'backward-word)
(global-set-key (kbd "C-c j") 'windmove-left)
(global-set-key (kbd "C-c k") 'windmove-right)
(global-set-key (kbd "C-c C-x m") 'set-mark-command)
(global-set-key (kbd "C-c ;") 'comment-region)
(global-set-key (kbd "C-c /") 'uncomment-region)
(global-set-key (kbd "C-c C-f") 'load-file)
(global-set-key (kbd "C-c C-x s") 'replace-string)
(global-set-key (kbd "C-c C-x <up>") 'enlarge-window-horizontally)
(global-set-key (kbd "C-c C-x <down>") 'shrink-window-horizontally)
(global-set-key (kbd "C-c C-x f") 'show-file-path)
(global-set-key (kbd "C-c C-x b") 'show-buffer-name)
(global-set-key (kbd "C-c C-x w") 'move-beginning-of-first-word)
(global-set-key (kbd "C-c C-x l") 'select-stripped-line)
(global-set-key (kbd "C-c C-x d") 'delete-stripped-line)
(global-set-key (kbd "C-c C-x x") 'delete-line)
(global-set-key (kbd "C-c C-x ;") 'comment-line)
(global-set-key (kbd "C-c C-x /") 'uncomment-line)
