(defun save-package-list-to-file (file)
  (setq tmp-list (copy-list package-activated-list))
  (setq package-list ())
  (dolist (p tmp-list)
	(push (symbol-name p) package-list))
  (setq package-list (sort package-list
						   (lambda (a b)
							 (string< a b))))
  (with-temp-buffer
	(dolist (p package-list)
	  (insert p)
	  (insert "\n"))
	(when (file-writable-p file)
	  (write-region (point-min)
					(point-max)
					file))))

(defun read-package-list-from-file (file)
  (when (file-readable-p file)
	(with-temp-buffer
	  (insert-file-contents file)
	  (setq tmp-list (split-string (buffer-string) "\n" t))))
  (setq package-list ())
  (dolist (p tmp-list)
	(push (make-symbol p) package-list))
  package-list)

(defun gen-non-activated-package-list-from-file (file)
  (setq non-activated-package-list ())
  (setq needed-package-list (read-package-list-from-file file))
  (dolist (p needed-package-list)
	(unless (package-installed-p p)
	  (setq non-activated-package-list
			(push p non-activated-package-list))))
  non-activated-package-list)

(defun install-packages (package-list)
  (dolist (p package-list)
	(unless (package-installed-p p)
	  (package-install p))))
